### ISSUE TITLE
Breaks fonts in lot of pages

### ISSUE THREAD

**Issue by kikonen-fiksu** [rapee/jsonfinder#30]
For example,

http://csswizardry.com/about/

With this plugin enabled, monospace font is shown, if not enabled, then correct font is shown. After some debugging I figured out that this extension is for some reason overriding font tried to be used by page.

**Comment by fibric** [comment]
the problem is that jsonfinder **always** injects its style.css regardless if json data is shown or not.
fonts form style.css priorize curier new on any non mac machines.

**Comment by rapee** [comment]
Fixed in 0.1.0
